import Head from "next/head"
import Image from "next/image"
// @ts-ignore
import styles from "../styles/Home.module.css"
import { useState, useEffect } from "react"
const ls = require("local-storage")

const VALUES = [
  "Creativity",
  "Ingenuity",
  "Fun",
  "Health",
  "Aesthetics",
  "Beauty",
  "Improvement",
  "Enthusiasm",
  "Enlightenment",
  "Friendship",
  "Gratitude",
  "Knowledge",
  "Intelligence",
  "Equality",
  "Compassion",
  "Simplicity",
]

export default function Home() {
  // read local state
  let savedValues
  let savedCombos
  if (ls.get("values") && ls.get("combos")) {
    savedValues = new Map()
    ls.get("values").forEach(([value, count]) => savedValues.set(value, count))
    savedCombos = new Map()
    try {
      ls.get("combos").forEach(([value1value2, [value1, value2]]) =>
        savedCombos.set(value1value2, [value1, value2])
      )
    } catch (e) {
      savedCombos.set("greatjob!☯", ["great", "job!☯"])
    }
  }
  const initialValues = new Map()
  VALUES.forEach((value) => {
    initialValues.set(value, 0)
  })
  const [values, setValues] = useState(savedValues || initialValues)

  const initialCombos = new Map()
  // generate combinations
  Array.from(values.keys()).forEach((value1) => {
    Array.from(values.keys()).forEach((value2) => {
      // remove duplicate, though it may make voting more accurate
      // since [value1, value2] & [value2, value1] votes may differ
      if (value1 !== value2 && !initialCombos.has(value2 + value1))
        initialCombos.set(value1 + value2, [value1, value2])
    })
  })
  const [combos, setCombos] = useState(savedCombos || initialCombos)

  const pickRandomValue = () => {
    try {
      return Array.from(combos.values())[
        Math.floor(Math.random() * combos.size)
      ]
    } catch (e) {
      return ["great", "job!☯"]
    }
  }

  const [value1, setValue1] = useState("great")
  const [value2, setValue2] = useState("job!☯")

  useEffect(() => {
    if (combos.size === 0) {
      setValue1("great")
      setValue2("job!☯")
      return
    }
    const [value1, value2] = pickRandomValue()
    setValue1(value1)
    setValue2(value2)
  }, [])

  const selectValue = (combo, value) => {
    setCombos((combos) => {
      combos.delete(combo)
      ls.set("combos", Array.from(combos))
      return combos
    })
    setValues((values) => {
      values.set(value, values.get(value) + 1)
      ls.set("values", Array.from(values))
      // sort Map based on vote count
      return new Map(
        Array.from(values).sort(
          ([value1, count1], [value2, count2]) => count1 - count2
        )
      )
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>What are your values?</h1>

        <div style={{ display: "flex", flexWrap: "wrap" }}>
          {Array.from(values).map(([value, count]) => (
            <p className={styles.description} key={value}>
              {value} <code className={styles.code}>{count}</code>
            </p>
          ))}
        </div>

        <div>
          <h2>Do you value...</h2>
          <div className={styles.grid}>
            <button
              onClick={() => selectValue(value1 + value2, value1)}
              className={styles.card}
            >
              <h2>{value1}</h2>
            </button>
            {combos.size >= 1 && <span className={styles.or}>or</span>}
            <button
              onClick={() => selectValue(value1 + value2, value2)}
              className={styles.card}
            >
              <h2>{value2}</h2>
            </button>
          </div>
        </div>

        <h3>Remaining combos: {combos.size}</h3>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.doctorderek.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          A DoctorDerek project
        </a>
      </footer>
    </div>
  )
}
