import Head from "next/head"
import Image from "next/image"
// @ts-ignore
import styles from "../styles/Home.module.css"
import { useState } from "react"

const VALUES = [
  "Creativity",
  "Ingenuity",
  "Fun",
  "Health",
  "Aesthetics",
  "Beauty",
  "Improvement",
  "Enthusiasm",
  "Enlightenment",
  "Friendship",
  "Gratitude",
  "Knowledge",
  "Intelligence",
  "Equality",
  "Compassion",
  "Simplicity",
]

export default function Home() {
  const initialValues = new Map()
  VALUES.forEach((value) => {
    initialValues.set(value, 0)
  })
  const [values, setValues] = useState(initialValues)

  const selectValue = (value) =>
    setValues((values) => {
      values.set(value, values.get(value) + 1)
      // sort Map based on vote count
      return new Map(
        Array.from(values).sort(
          ([value1, count1], [value2, count2]) => count1 - count2
        )
      )
    })

  const pickRandomValue = () =>
    Array.from(values.keys())[Math.floor(Math.random() * values.size)]
  const value1 = pickRandomValue()
  const value2 = pickRandomValue()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>What are your values?</h1>

        <div style={{ display: "flex", flexWrap: "wrap" }}>
          {Array.from(values).map(([value, count]) => (
            <p className={styles.description}>
              {value} <code className={styles.code}>{count}</code>
            </p>
          ))}
        </div>

        <div className={styles.grid}>
          <button onClick={() => selectValue(value1)} className={styles.card}>
            <h2>{value1}</h2>
          </button>

          <button onClick={() => selectValue(value2)} className={styles.card}>
            <h2>{value2}</h2>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
